FROM quay.io/pypa/manylinux_2_34_x86_64
RUN yum install -y gcc openssl-devel bzip2-devel libffi-devel wget make
RUN cd /tmp && \
    wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz && \
    tar xzf Python-3.13.0.tgz && \
    cd Python-3.13.0 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall
RUN python3.13 -m ensurepip
RUN python3.13 -m pip install --upgrade pip setuptools wheel auditwheel cython
COPY . /project
WORKDIR /project
RUN python3.13 setup.py bdist_wheel
RUN mkdir -p /wheelhouse && auditwheel repair dist/*.whl -w /wheelhouse