name: Create Debian Structure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Debian package structure
      run: |
        chmod +x create_debian_structure.sh
        ./create_debian_structure.sh
